
#-- gestures supported by Otto
OTTOHAPPY      = 0
OTTOSUPERHAPPY = 1
OTTOSAD        = 2
OTTOSLEEPING   = 3
OTTOFART       = 4
OTTOCONFUSED   = 5
OTTOLOVE       = 6
OTTOANGRY      = 7
OTTOFRETFUL    = 8
OTTOMAGIC      = 9
OTTOWAVE       = 10
OTTOVICTORY    = 11
OTTOFAIL       = 12
