#-- Song CONSTANTS for otto9
#-- OttDIY Python Project, 2020

CONNECTION    = const(0)
DISCONNECTION = const(1)
SURPRISE      = const(2)
OHOOH         = const(3)
OHOOH2        = const(4)
CUDDLY        = const(5)
SLEEPING      = const(6)
HAPPY         = const(7)
SUPERHAPPY    = const(8)
HAPPYSHORT    = const(9)
SAD           = const(10)
CONFUSED      = const(11)
FART1         = const(12)
FART2         = const(13)
FART3         = const(14)
MODE1         = const(15)
MODE2         = const(16)
MODE3         = const(17)
BUTTONPUSHED  = const(18)
